title: vulnWorkbench
description: vulnWorkbenchは、複数のセキュリティスキャナーによる検査結果と証跡をまとめ、何をどこまで調べたかが分かるレポートをローカル環境に残します。
lang: ja
url: "https://ugnoguchigxp.github.io"
baseurl: "/vlunWorkbench"
repository: "ugnoguchigxp/vlunWorkbench"

source: site
destination: docs

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

include:
  - .nojekyll

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
