import type { ScanExecutionPlan } from "../../../../shared/schemas/scan-execution-plan.schema";
import type { ScanPreflightResult } from "../../../../shared/schemas/scan-preflight.schema";
import type { AppDatabase } from "../../../db";
import type { RuntimeTargetProvider } from "../../dast/runtime-target-provider";
import type { ProjectCapabilityAnalysis } from "../../project-capabilities/plugin-detector";
import type { getProfileById } from "../profiles";
import type { ScanRepository } from "../repositories";
import type { resolveScanScope } from "../target-scope";
import type { ToolExecutionConfig } from "../tools/tool-process-runner";
import type { DiffScanPlan } from "./diff/diff-scan-plan";
import type { DiffSnapshot } from "./diff/diff-snapshot";
import type { ArtifactStorage } from "./lifecycle/artifact-storage";
import type { resolveProfileSteps } from "./profile-runner";

export type ExecuteProfileStepsParams = {
	db: AppDatabase;
	projectId: string;
	repoPath: string;
	profileInputRepoPath: string;
	timeoutSec?: number;
	createdByUserId?: string | null;
	imageRef?: string;
	imageTar?: string;
	attestationSubject?: string;
	attestationBundle?: string;
	trustPolicy?: string;
	scanRepo: ScanRepository;
	scanRun: { id: string };
	profile: NonNullable<ReturnType<typeof getProfileById>>;
	profileSteps: ReturnType<typeof resolveProfileSteps>;
	continueOnToolFailure: boolean;
	diffPlan: DiffScanPlan | null;
	diffSnapshot: DiffSnapshot | null;
	sharesRuntimeTarget: boolean;
	resolvedScope: Awaited<ReturnType<typeof resolveScanScope>>;
	artifactStorage: ArtifactStorage;
	execution: ToolExecutionConfig;
	technologyAnalysis: ProjectCapabilityAnalysis;
	consentProjectCodeExecution: boolean;
	runtimeTargetProvider?: RuntimeTargetProvider;
	scanPreflight: ScanPreflightResult;
	executionPlan: ScanExecutionPlan;
};
