import { z } from "zod";

export const scanReasonCodeCategorySchema = z.enum([
	"applicability",
	"readiness",
	"policy",
	"execution",
	"cleanup",
	"coverage",
]);
export type ScanReasonCodeCategory = z.infer<
	typeof scanReasonCodeCategorySchema
>;

export const scanReasonCodeSchema = z.enum([
	"schema_not_found",
	"authentication_required",
	"auth_context_missing",
	"image_input_not_provided",
	"image_source_unreachable",
	"attestation_input_missing",
	"attestation_verification_failed",
	"slsa_trust_root_network_required",
	"target_start_not_supported",
	"target_unreachable_from_container",
	"preflight_failed",
	"tool_unavailable",
	"policy_rejected",
	"roe_not_approved",
	"invalid_structured_output",
	"timed_out",
	"execution_failed",
	"cleanup_failed",
	"resource_quarantined",
	"crawl_budget_exhausted",
	"role_matrix_partial",
	"source_sast_not_executed",
	"source_sast_no_supported_files",
	"source_sast_ruleset_unavailable",
	"source_sast_adapter_unavailable",
	"capability_not_integrated",
	"no_changed_files",
	"no_relevant_files",
	"no_dependency_manifest_changed",
	"diff_target_not_supported",
	"profile_platform_not_qualified",
	"required_capability_missing",
	"openapi_schema_required",
	"openapi_yaml_not_qualified",
	"openapi_version_not_qualified",
	"openapi_external_ref_rejected",
	"openapi_callback_not_qualified",
	"no_unauthenticated_readonly_operations",
	"original_execution_identity_missing",
	"comparison_identity_mismatch",
	"legacy_custom_reproduction_not_supported",
	"custom_dynamic_config_not_stable",
	"no_tests_collected",
	"authentication_assertion_required",
	"target_authorization_required",
	"target_lease_required",
	"target_reset_failed",
	"business_logic_v2_required",
	"unknown_reason_code",
]);
export type ScanReasonCode = z.infer<typeof scanReasonCodeSchema>;

export const scanReasonCodeDefinitionSchema = z.object({
	category: scanReasonCodeCategorySchema,
	coverageEffect: z.enum(["covered", "partial", "gap"]),
	action: z.string().min(1).max(100),
	messageKey: z.string().regex(/^[a-z][a-z0-9_]{2,99}$/),
});
export type ScanReasonCodeDefinition = z.infer<
	typeof scanReasonCodeDefinitionSchema
>;

export const scanReasonCodeRegistry = {
	schema_not_found: {
		category: "applicability",
		coverageEffect: "gap",
		action: "configure_api_schema",
		messageKey: "schema_not_found",
	},
	authentication_required: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_auth_context",
		messageKey: "authentication_required",
	},
	auth_context_missing: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_auth_context",
		messageKey: "auth_context_missing",
	},
	image_input_not_provided: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_image_input",
		messageKey: "image_input_not_provided",
	},
	image_source_unreachable: {
		category: "readiness",
		coverageEffect: "gap",
		action: "make_image_source_reachable",
		messageKey: "image_source_unreachable",
	},
	attestation_input_missing: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_attestation_inputs",
		messageKey: "attestation_input_missing",
	},
	attestation_verification_failed: {
		category: "execution",
		coverageEffect: "gap",
		action: "inspect_attestation_and_trust_policy",
		messageKey: "attestation_verification_failed",
	},
	slsa_trust_root_network_required: {
		category: "readiness",
		coverageEffect: "gap",
		action: "allow_slsa_trust_root_network",
		messageKey: "slsa_trust_root_network_required",
	},
	target_start_not_supported: {
		category: "applicability",
		coverageEffect: "gap",
		action: "configure_target_start_plan",
		messageKey: "target_start_not_supported",
	},
	target_unreachable_from_container: {
		category: "readiness",
		coverageEffect: "gap",
		action: "configure_container_target_gateway",
		messageKey: "target_unreachable_from_container",
	},
	preflight_failed: {
		category: "readiness",
		coverageEffect: "gap",
		action: "resolve_preflight_blockers",
		messageKey: "preflight_failed",
	},
	tool_unavailable: {
		category: "readiness",
		coverageEffect: "gap",
		action: "install_or_pin_tool",
		messageKey: "tool_unavailable",
	},
	policy_rejected: {
		category: "policy",
		coverageEffect: "gap",
		action: "review_scan_policy",
		messageKey: "policy_rejected",
	},
	roe_not_approved: {
		category: "policy",
		coverageEffect: "gap",
		action: "approve_rules_of_engagement",
		messageKey: "roe_not_approved",
	},
	invalid_structured_output: {
		category: "execution",
		coverageEffect: "gap",
		action: "inspect_tool_output",
		messageKey: "invalid_structured_output",
	},
	timed_out: {
		category: "execution",
		coverageEffect: "gap",
		action: "review_timeout_and_budget",
		messageKey: "timed_out",
	},
	execution_failed: {
		category: "execution",
		coverageEffect: "gap",
		action: "inspect_execution_failure",
		messageKey: "execution_failed",
	},
	cleanup_failed: {
		category: "cleanup",
		coverageEffect: "gap",
		action: "run_manual_cleanup",
		messageKey: "cleanup_failed",
	},
	resource_quarantined: {
		category: "cleanup",
		coverageEffect: "gap",
		action: "recover_quarantined_resource",
		messageKey: "resource_quarantined",
	},
	crawl_budget_exhausted: {
		category: "coverage",
		coverageEffect: "partial",
		action: "review_crawl_budget",
		messageKey: "crawl_budget_exhausted",
	},
	role_matrix_partial: {
		category: "coverage",
		coverageEffect: "partial",
		action: "provide_missing_roles",
		messageKey: "role_matrix_partial",
	},
	source_sast_not_executed: {
		category: "coverage",
		coverageEffect: "gap",
		action: "run_source_sast",
		messageKey: "source_sast_not_executed",
	},
	source_sast_no_supported_files: {
		category: "applicability",
		coverageEffect: "covered",
		action: "provide_supported_source_files",
		messageKey: "source_sast_no_supported_files",
	},
	source_sast_ruleset_unavailable: {
		category: "readiness",
		coverageEffect: "gap",
		action: "install_or_pin_ruleset",
		messageKey: "source_sast_ruleset_unavailable",
	},
	source_sast_adapter_unavailable: {
		category: "readiness",
		coverageEffect: "gap",
		action: "install_or_pin_tool",
		messageKey: "source_sast_adapter_unavailable",
	},
	capability_not_integrated: {
		category: "coverage",
		coverageEffect: "gap",
		action: "integrate_capability",
		messageKey: "capability_not_integrated",
	},
	no_changed_files: {
		category: "applicability",
		coverageEffect: "covered",
		action: "select_changed_files",
		messageKey: "no_changed_files",
	},
	no_relevant_files: {
		category: "applicability",
		coverageEffect: "covered",
		action: "select_relevant_files",
		messageKey: "no_relevant_files",
	},
	no_dependency_manifest_changed: {
		category: "applicability",
		coverageEffect: "covered",
		action: "select_dependency_manifest",
		messageKey: "no_dependency_manifest_changed",
	},
	diff_target_not_supported: {
		category: "applicability",
		coverageEffect: "gap",
		action: "select_supported_target",
		messageKey: "diff_target_not_supported",
	},
	profile_platform_not_qualified: {
		category: "readiness",
		coverageEffect: "gap",
		action: "qualify_platform",
		messageKey: "profile_platform_not_qualified",
	},
	required_capability_missing: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_required_capability",
		messageKey: "required_capability_missing",
	},
	openapi_schema_required: {
		category: "applicability",
		coverageEffect: "gap",
		action: "configure_api_schema",
		messageKey: "openapi_schema_required",
	},
	openapi_yaml_not_qualified: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provide_openapi_json",
		messageKey: "openapi_yaml_not_qualified",
	},
	openapi_version_not_qualified: {
		category: "readiness",
		coverageEffect: "gap",
		action: "use_supported_openapi_version",
		messageKey: "openapi_version_not_qualified",
	},
	openapi_external_ref_rejected: {
		category: "policy",
		coverageEffect: "gap",
		action: "bundle_openapi_refs",
		messageKey: "openapi_external_ref_rejected",
	},
	openapi_callback_not_qualified: {
		category: "policy",
		coverageEffect: "gap",
		action: "remove_callbacks_or_use_experimental",
		messageKey: "openapi_callback_not_qualified",
	},
	no_unauthenticated_readonly_operations: {
		category: "applicability",
		coverageEffect: "gap",
		action: "use_authenticated_web_profile",
		messageKey: "no_unauthenticated_readonly_operations",
	},
	original_execution_identity_missing: {
		category: "applicability",
		coverageEffect: "gap",
		action: "run_new_source_scan",
		messageKey: "original_execution_identity_missing",
	},
	comparison_identity_mismatch: {
		category: "execution",
		coverageEffect: "gap",
		action: "restore_original_scanner_binding",
		messageKey: "comparison_identity_mismatch",
	},
	legacy_custom_reproduction_not_supported: {
		category: "policy",
		coverageEffect: "gap",
		action: "use_stable_verification_preview",
		messageKey: "legacy_custom_reproduction_not_supported",
	},
	custom_dynamic_config_not_stable: {
		category: "policy",
		coverageEffect: "gap",
		action: "use_experimental_dynamic_lab",
		messageKey: "custom_dynamic_config_not_stable",
	},
	no_tests_collected: {
		category: "coverage",
		coverageEffect: "gap",
		action: "add_test_cases",
		messageKey: "no_tests_collected",
	},
	authentication_assertion_required: {
		category: "readiness",
		coverageEffect: "gap",
		action: "configure_auth_readiness",
		messageKey: "authentication_assertion_required",
	},
	target_authorization_required: {
		category: "policy",
		coverageEffect: "gap",
		action: "approve_target_authorization",
		messageKey: "target_authorization_required",
	},
	target_lease_required: {
		category: "readiness",
		coverageEffect: "gap",
		action: "provision_runtime_bundle",
		messageKey: "target_lease_required",
	},
	target_reset_failed: {
		category: "cleanup",
		coverageEffect: "gap",
		action: "inspect_quarantined_resource",
		messageKey: "target_reset_failed",
	},
	business_logic_v2_required: {
		category: "readiness",
		coverageEffect: "gap",
		action: "migrate_scenario_v2",
		messageKey: "business_logic_v2_required",
	},
	unknown_reason_code: {
		category: "execution",
		coverageEffect: "gap",
		action: "update_client_and_registry",
		messageKey: "unknown_reason_code",
	},
} as const satisfies Record<ScanReasonCode, ScanReasonCodeDefinition>;

export function getScanReasonCodeDefinition(
	code: ScanReasonCode,
): ScanReasonCodeDefinition {
	return scanReasonCodeRegistry[code];
}
