import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { buildScanProfiles } from "../api/modules/scans/profiles";
import {
	scanPreflightBindingSchema,
	scanPreflightCheckKindSchema,
	scanPreflightModeSchema,
} from "../shared/schemas/scan-preflight.schema";
import type { ScanProfileStep } from "../shared/schemas/scan-profile.schema";
import { scannerDataManifestV2Schema } from "../shared/schemas/security-capability.schema";

const root = process.cwd();
const outputPath = path.join(
	root,
	"docs/generated/security-capability-table.md",
);
const manifestPath = path.join(
	root,
	"docker/toolbox/scanner-data/scanner-data-manifest.json",
);

function stepId(step: ScanProfileStep): string {
	if (step.kind === "static_tool") return step.toolId;
	if (step.kind === "dast") return `dast:${step.profileId}`;
	return `${step.kind}:${step.adapter}`;
}

function cell(values: string[]): string {
	return values.length > 0 ? values.join("<br>") : "—";
}

export async function buildSecurityCapabilityDocument(): Promise<string> {
	const manifest = scannerDataManifestV2Schema.parse(
		JSON.parse(await fs.readFile(manifestPath, "utf8")),
	);
	const coreProfileIds = new Set(
		buildScanProfiles({ optionalAdapterIds: [] }).map((profile) => profile.id),
	);
	const profiles = buildScanProfiles({ optionalAdapterIds: ["semgrep"] }).sort(
		(left, right) => left.id.localeCompare(right.id),
	);
	const scannerRows = Object.entries(manifest.tools)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([toolId, tool]) => {
			const bundles = tool.dataBundles.map(
				(bundle) => `${bundle.id} (${bundle.kind}, ${bundle.digest})`,
			);
			return `| ${toolId} | ${tool.version} | ${tool.state} | ${tool.runtimePath ? "required" : "none"} | ${cell(bundles)} |`;
		});
	const profileRows = profiles.map((profile) => {
		const steps: ScanProfileStep[] =
			profile.steps ??
			profile.tools.map((tool) => ({ kind: "static_tool" as const, ...tool }));
		return `| ${profile.id} | ${coreProfileIds.has(profile.id) ? "core" : "optional adapter"} | ${cell(steps.filter((step) => step.required).map(stepId))} | ${cell(steps.filter((step) => !step.required).map(stepId))} | ${cell(profile.coverageGaps ?? [])} |`;
	});
	const sourceHash = `sha256:${crypto
		.createHash("sha256")
		.update(
			JSON.stringify({
				manifestHash: manifest.manifestHash,
				profiles,
				preflightModes: scanPreflightModeSchema.options,
				preflightChecks: scanPreflightCheckKindSchema.options,
				preflightBinding: Object.keys(scanPreflightBindingSchema.shape),
			}),
		)
		.digest("hex")}`;

	return [
		"<!-- Generated by scripts/security-capability-docs.ts. Do not edit. -->",
		"# Security capability table",
		"",
		`Source contract hash: \`${sourceHash}\``,
		`Scanner manifest: \`${manifest.manifestHash}\``,
		"",
		"This table describes configured capability and readiness contracts. It is not evidence that a scanner ran successfully on a particular project; stored scan preflight and coverage results remain authoritative for each run.",
		"",
		"## Scanner inputs",
		"",
		"| Scanner | Version | Manifest state | Runtime data | Pinned data bundles |",
		"| --- | --- | --- | --- | --- |",
		...scannerRows,
		"",
		"## Scan profiles",
		"",
		"| Profile | Availability | Required steps | Optional steps | Declared coverage gaps |",
		"| --- | --- | --- | --- | --- |",
		...profileRows,
		"",
		"## Preflight contract",
		"",
		`Modes: ${scanPreflightModeSchema.options.map((value) => `\`${value}\``).join(", ")}.`,
		"",
		`Checks: ${scanPreflightCheckKindSchema.options.map((value) => `\`${value}\``).join(", ")}.`,
		"",
		`Drift binding: ${Object.keys(scanPreflightBindingSchema.shape)
			.map((value) => `\`${value}\``)
			.join(", ")}.`,
		"",
		"In `enforced` mode, a blocked required check fails before any scanner starts. A blocked optional check is recorded as a coverage gap. `shadow` mode records the same result without changing admission.",
		"",
	].join("\n");
}

const document = await buildSecurityCapabilityDocument();
if (process.argv.includes("--check")) {
	const stored = await fs.readFile(outputPath, "utf8").catch(() => "");
	if (stored !== document) {
		console.error(
			"Generated security capability documentation is stale. Run `bun run docs:security-capability`.",
		);
		process.exit(1);
	}
	console.log("Security capability documentation is current.");
} else {
	await fs.mkdir(path.dirname(outputPath), { recursive: true });
	await fs.writeFile(outputPath, document, "utf8");
	console.log(path.relative(root, outputPath));
}
