import crypto from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildScanProfiles } from "../api/modules/scans/profiles";
import {
	scanPreflightBindingSchema,
	scanPreflightCheckKindSchema,
	scanPreflightModeSchema,
} from "../shared/schemas/scan-preflight.schema";
import type { ScanProfileStep } from "../shared/schemas/scan-profile.schema";
import { scannerDataManifestV2Schema } from "../shared/schemas/security-capability.schema";

const root = process.cwd();
const outputPath = path.join(
	root,
	"spec/generated/security-capability-table.html",
);
const manifestPath = path.join(
	root,
	"docker/toolbox/scanner-data/scanner-data-manifest.json",
);

function stepId(step: ScanProfileStep): string {
	if (step.kind === "static_tool") return step.toolId;
	if (step.kind === "dast") return `dast:${step.profileId}`;
	return `${step.kind}:${step.adapter}`;
}

function escapeHtml(value: string): string {
	return value
		.replaceAll("&", "&amp;")
		.replaceAll("<", "&lt;")
		.replaceAll(">", "&gt;")
		.replaceAll('"', "&quot;")
		.replaceAll("'", "&#39;");
}

function code(value: string): string {
	return `<code>${escapeHtml(value)}</code>`;
}

function cell(values: string[], render = code): string {
	return values.length > 0 ? values.map(render).join("<br />") : "—";
}

async function formatSpecHtml(document: string): Promise<string> {
	const temporaryDirectory = await fs.mkdtemp(
		path.join(os.tmpdir(), "vuln-workbench-docs-"),
	);
	const temporaryPath = path.join(
		temporaryDirectory,
		"security-capability-table.html",
	);
	try {
		await fs.writeFile(temporaryPath, document, "utf8");
		const formatter = Bun.spawn(
			["bunx", "--bun", "spec-html", "format", temporaryPath, "--write"],
			{ stdout: "pipe", stderr: "pipe" },
		);
		const [exitCode, stdout, stderr] = await Promise.all([
			formatter.exited,
			new Response(formatter.stdout).text(),
			new Response(formatter.stderr).text(),
		]);
		if (exitCode !== 0) {
			throw new Error(
				`Failed to format generated Spec HTML: ${stderr || stdout}`.trim(),
			);
		}
		return await fs.readFile(temporaryPath, "utf8");
	} finally {
		await fs.rm(temporaryDirectory, { recursive: true, force: true });
	}
}

export async function buildSecurityCapabilityDocument(): Promise<string> {
	const manifest = scannerDataManifestV2Schema.parse(
		JSON.parse(await fs.readFile(manifestPath, "utf8")),
	);
	const coreProfileIds = new Set(
		buildScanProfiles({ optionalAdapterIds: [] }).map((profile) => profile.id),
	);
	const profiles = buildScanProfiles({ optionalAdapterIds: ["semgrep"] }).sort(
		(left, right) => left.id.localeCompare(right.id),
	);
	const scannerRows = Object.entries(manifest.tools)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(([toolId, tool]) => {
			const bundles = tool.dataBundles.map(
				(bundle) =>
					`${code(bundle.id)} (${escapeHtml(bundle.kind)}, ${code(bundle.digest)})`,
			);
			return `<tr><td>${code(toolId)}</td><td>${code(tool.version)}</td><td>${escapeHtml(tool.state)}</td><td>${tool.runtimePath ? "required" : "none"}</td><td>${cell(bundles, (value) => value)}</td></tr>`;
		});
	const profileRows = profiles.map((profile) => {
		const steps: ScanProfileStep[] =
			profile.steps ??
			profile.tools.map((tool) => ({ kind: "static_tool" as const, ...tool }));
		return `<tr><td>${code(profile.id)}</td><td>${coreProfileIds.has(profile.id) ? "core" : "optional adapter"}</td><td>${cell(steps.filter((step) => step.required).map(stepId))}</td><td>${cell(steps.filter((step) => !step.required).map(stepId))}</td><td>${cell(profile.coverageGaps ?? [])}</td></tr>`;
	});
	const sourceHash = `sha256:${crypto
		.createHash("sha256")
		.update(
			JSON.stringify({
				manifestHash: manifest.manifestHash,
				profiles,
				preflightModes: scanPreflightModeSchema.options,
				preflightChecks: scanPreflightCheckKindSchema.options,
				preflightBinding: Object.keys(scanPreflightBindingSchema.shape),
			}),
		)
		.digest("hex")}`;

	return formatSpecHtml(`<!-- Generated by scripts/security-capability-docs.ts. Do not edit. -->
<article lang="en">
<h1>Security capability table</h1>
<p>Source contract hash: ${code(sourceHash)}<br />Scanner manifest: ${code(manifest.manifestHash)}</p>
<p>This table describes configured capability and readiness contracts. It is not evidence that a scanner ran successfully on a particular project; stored scan preflight and coverage results remain authoritative for each run.</p>
<h2>Scanner inputs</h2>
<table><caption>Scanner inputs</caption><thead><tr><th scope="col">Scanner</th><th scope="col">Version</th><th scope="col">Manifest state</th><th scope="col">Runtime data</th><th scope="col">Pinned data bundles</th></tr></thead><tbody>${scannerRows.join("")}</tbody></table>
<h2>Scan profiles</h2>
<table><caption>Scan profiles</caption><thead><tr><th scope="col">Profile</th><th scope="col">Availability</th><th scope="col">Required steps</th><th scope="col">Optional steps</th><th scope="col">Declared coverage gaps</th></tr></thead><tbody>${profileRows.join("")}</tbody></table>
<h2>Preflight contract</h2>
<p>Modes: ${scanPreflightModeSchema.options.map(code).join(", ")}.</p>
<p>Checks: ${scanPreflightCheckKindSchema.options.map(code).join(", ")}.</p>
<p>Drift binding: ${Object.keys(scanPreflightBindingSchema.shape).map(code).join(", ")}.</p>
<p>In ${code("enforced")} mode, a blocked required check fails before any scanner starts. A blocked optional check is recorded as a coverage gap. ${code("shadow")} mode records the same result without changing admission.</p>
</article>
`);
}

const document = await buildSecurityCapabilityDocument();
if (process.argv.includes("--check")) {
	const stored = await fs.readFile(outputPath, "utf8").catch(() => "");
	if (stored !== document) {
		console.error(
			"Generated security capability documentation is stale. Run `bun run docs:security-capability`.",
		);
		process.exit(1);
	}
	console.log("Security capability documentation is current.");
} else {
	await fs.mkdir(path.dirname(outputPath), { recursive: true });
	await fs.writeFile(outputPath, document, "utf8");
	console.log(path.relative(root, outputPath));
}
