import { describe, expect, test } from "bun:test";
import { getTableName } from "drizzle-orm";
import * as schema from "../schema";

const tableExports = [
	"users",
	"refreshTokens",
	"sources",
	"sourceFragments",
	"conversations",
	"messages",
	"artifacts",
	"retrievalLogs",
	"userSettings",
	"llmProviderEndpoints",
	"llmTaskRoutes",
	"llmProviderHealthChecks",
	"integrationClients",
	"integrationResourceBindings",
	"integrationIdempotencyKeys",
	"integrationPreviews",
	"integrationAuditLogs",
	"projects",
	"scanRuns",
	"staticIntelligencePrepareJobs",
	"scanEvents",
	"toolRuns",
	"scanArtifacts",
	"findings",
	"findingEvidences",
	"findingReviews",
	"findingDecisions",
	"scanReports",
	"scanReviews",
	"staticIntelligenceEmbeddings",
	"attackSurfaceItems",
	"securityChecks",
	"securityCheckResults",
	"diagnosticReports",
	"reproductionRuns",
	"reproductionArtifacts",
	"reproductionEvidence",
	"dynamicProfileConfigs",
	"dynamicRuns",
	"dynamicArtifacts",
	"dynamicEvidence",
	"dastTargetConfigs",
	"dastProfileConfigs",
	"dastRuns",
	"dastArtifacts",
	"dastEvidence",
] as const;

describe("database schema module contract", () => {
	test("preserves the public table export and SQL-name inventory", () => {
		expect(
			tableExports.map((exportName) => getTableName(schema[exportName])),
		).toEqual([
			"users",
			"refresh_tokens",
			"sources",
			"source_fragments",
			"conversations",
			"messages",
			"artifacts",
			"retrieval_logs",
			"user_settings",
			"llm_provider_endpoints",
			"llm_task_routes",
			"llm_provider_health_checks",
			"integration_clients",
			"integration_resource_bindings",
			"integration_idempotency_keys",
			"integration_previews",
			"integration_audit_logs",
			"projects",
			"scan_runs",
			"static_intelligence_prepare_jobs",
			"scan_events",
			"tool_runs",
			"scan_artifacts",
			"findings",
			"finding_evidence",
			"finding_reviews",
			"finding_decisions",
			"scan_reports",
			"scan_reviews",
			"static_intelligence_embeddings",
			"attack_surface_items",
			"security_checks",
			"security_check_results",
			"diagnostic_reports",
			"reproduction_runs",
			"reproduction_artifacts",
			"reproduction_evidence",
			"dynamic_profile_configs",
			"dynamic_runs",
			"dynamic_artifacts",
			"dynamic_evidence",
			"dast_target_configs",
			"dast_profile_configs",
			"dast_runs",
			"dast_artifacts",
			"dast_evidence",
		]);
	});
});
